import './globals.css';
import type { Metadata } from 'next';
import Providers from '@/provider/providers';
import { lato } from '@/fonts/fonts';
import Footer from '@/components/footer';
import NavBar from '../components/header/navbar';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lato.className}>
      <body>
        <Providers>
          <div className=" flex flex-col h-full overflow-hidden">
            <NavBar />
            <div className=" grow ">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
