import './globals.css';
import type { Metadata } from 'next';
import Navbar from '@/components/header/navbar';
import Providers from '@/provider/providers';
import { lato } from '@/fonts/fonts';
import Footer from '@/components/footer';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={lato.className}>
      <body className=" min-h-screen">
        <Providers>
          <div className=" flex flex-col h-full overflow-hidden">
            {/*@ts-expect-error server component */}
            <Navbar />

            <div className=" grow ">{children}</div>
            <Footer />
          </div>
        </Providers>
      </body>
    </html>
  );
}
